"""change Task index

Revision ID: 30e6707f091b
Revises: 6a23b3396544
Create Date: 2025-10-08 10:45:46.246380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30e6707f091b'
down_revision: Union[str, None] = '6a23b3396544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_name_args_hash', table_name='celery_tasks')
    op.create_index('ix_task_name_args_hash', 'celery_tasks', ['task_name', 'task_args_hash', 'task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_name_args_hash', table_name='celery_tasks')
    op.create_index('ix_task_name_args_hash', 'celery_tasks', ['task_name', 'task_args_hash'], unique=True)
    # ### end Alembic commands ###
