"""create celery_task table

Revision ID: 6a23b3396544
Revises: d2c3e9d5ff1a
Create Date: 2025-10-07 16:53:45.381089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a23b3396544'
down_revision: Union[str, None] = 'd2c3e9d5ff1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('task_args_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('task_args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_celery_task_id', 'celery_tasks', ['task_id'], unique=False)
    op.create_index('ix_task_execution_created_at', 'celery_tasks', ['created_at'], unique=False)
    op.create_index('ix_task_execution_status', 'celery_tasks', ['status'], unique=False)
    op.create_index('ix_task_name_args_hash', 'celery_tasks', ['task_name', 'task_args_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_name_args_hash', table_name='celery_tasks')
    op.drop_index('ix_task_execution_status', table_name='celery_tasks')
    op.drop_index('ix_task_execution_created_at', table_name='celery_tasks')
    op.drop_index('ix_celery_task_id', table_name='celery_tasks')
    op.drop_table('celery_tasks')
    # ### end Alembic commands ###
