"""create celery_task table

Revision ID: d2c3e9d5ff1a
Revises: 3230b0638aaf
Create Date: 2025-10-07 16:46:57.547110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2c3e9d5ff1a'
down_revision: Union[str, None] = '3230b0638aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    indexes = inspector.get_indexes('collection_1024_9bcdcdea-ecb0-4f1f-9866-9a23b4ed82c6')
    index_names = [idx['name'] for idx in indexes]
    if 'collection_1024_9bcdcdea-ecb0-4f1f-9866-9a23b4ed82c6_vector_idx' in index_names:
        op.drop_index('collection_1024_9bcdcdea-ecb0-4f1f-9866-9a23b4ed82c6_vector_idx', table_name='collection_1024_9bcdcdea-ecb0-4f1f-9866-9a23b4ed82c6', postgresql_using='hnsw')
    op.drop_table('collection_1024_9bcdcdea-ecb0-4f1f-9866-9a23b4ed82c6')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_1024_9bcdcdea-ecb0-4f1f-9866-9a23b4ed82c6',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name='collection_1024_9bcdcdea-ecb0-4f1f-9866-9a23b4ed8_chunk_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='collection_1024_9bcdcdea-ecb0-4f1f-9866-9a23b4ed82c6_pkey')
    )
    op.create_index('collection_1024_9bcdcdea-ecb0-4f1f-9866-9a23b4ed82c6_vector_idx', 'collection_1024_9bcdcdea-ecb0-4f1f-9866-9a23b4ed82c6', ['vector'], unique=False, postgresql_using='hnsw')
    # ### end Alembic commands ###
